name: Test Notify Third Party

on:
  workflow_dispatch:
    inputs:
      test_platform:
        description: "Test platform"
        required: true
        default: "qywx"
        type: choice
        options:
          - qywx
          - feishu
          - dingtalk
          - teams
          - qywx,feishu
          - qywx,feishu,dingtalk
          - qywx,feishu,dingtalk,teams
      test_status:
        description: "Test status"
        required: true
        default: "success"
        type: choice
        options:
          - success
          - failure
          - warning

jobs:
  test-notify:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/notify-third.yml
    with:
      env: "test"
      version: "v1.0.0-test"
      preview_url: "https://example.com/test"
      project_name: "测试项目"
      third_type: ${{ github.event.inputs.test_platform }}
      status: ${{ github.event.inputs.test_status }}
    secrets:
      WEBHOOK_QYWX: ${{ secrets.WEBHOOK_QYWX }}
      WEBHOOK_FEISHU: ${{ secrets.WEBHOOK_FEISHU }}
      WEBHOOK_DINGTALK: ${{ secrets.WEBHOOK_DINGTALK }}
      WEBHOOK_TEAMS: ${{ secrets.WEBHOOK_TEAMS }} 