name: Auto Increment Tag

on:
  workflow_call:
    inputs:
      version_type:
        description: "Version increment type (major, feat, fix)"
        required: true
        type: string
        default: "fix"

    outputs:
      new_version:
        description: "The new version after increment"
        value: ${{ jobs.increment-tag.outputs.new_version }}

  workflow_dispatch:
    inputs:
      version_type:
        description: "Version increment type (major, feat, fix)"
        required: true
        type: choice
        default: "fix"
        options:
          - fix
          - feat
          - major

jobs:
  increment-tag:
    runs-on: ubuntu-latest

    outputs:
      new_version: ${{ steps.increment_version.outputs.new_version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(git tag -l --sort=-v:refname | head -n 1 || echo "v0.0.0")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        shell: /usr/bin/bash -e {0}

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${LATEST_TAG#v}
          MAJOR=$(echo $VERSION | cut -d. -f1 || echo 0)
          FEAT=$(echo $VERSION | cut -d. -f2 || echo 0)
          FIX=$(echo $VERSION | cut -d. -f3 || echo 0)

          if [ "${{ inputs.version_type }}" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            FEAT=0
            FIX=0
          elif [ "${{ inputs.version_type }}" == "feat" ]; then
            FEAT=$((FEAT + 1))
            FIX=0
          else
            FIX=$((FIX + 1))
          fi

          NEW_VERSION="v${MAJOR}.${FEAT}.${FIX}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.increment_version.outputs.new_version }}
          git push origin ${{ steps.increment_version.outputs.new_version }}
