name: Deploy Statistics

run-name: Deploy Statistics

on:
  workflow_call:
    inputs:
      gh_token:
        description: "github.token"
        required: true
        type: string
        default: "--"

      version:
        description: "Version"
        required: true
        type: string
        default: "--"

      env:
        description: "Environment type (PROD, UAT)"
        required: true
        type: string
        default: "--"

  workflow_dispatch:
    inputs:
      gh_token:
        description: "github.token"
        required: true
        type: string
        default: "--"

      version:
        description: "Version"
        required: true
        type: string
        default: "v0.1.2"

      env:
        description: "Environment type (PROD, UAT)"
        required: true
        type: string
        default: "PROD"

# RELEASE_NUMBER = $(echo ${{ github.ref }} | cut -d '/' -f 4)
jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Console Params
        run: |
          echo "=== [Console Params][params] gh_token: ${{inputs.gh_token}} ==="
          echo "=== [Console Params][params] repository: ${{github.repository}} ==="
          echo "=== [Console Params][params] project_name: ${{github.event.repository.name}} ==="
          echo "=== [Console Params][params] ref_name: ${{github.ref_name}} ==="
          echo "=== [Console Params][params] release_number: #11 ==="
          echo "=== [Console Params][params] version: ${{inputs.version}} ==="
          echo "=== [Console Params][params] env: ${{inputs.env}} ==="
          echo "=== [Console Params][params] actor: ${{github.actor}} ==="

      - name: Get deployment info
        id: get_deploy
        env:
          GH_TOKEN: ${{ inputs.gh_token }}
        run: |
          echo "=== [Get deployment info][params] repository: ${{github.repository}} ==="
          echo "=== [Get deployment info][params] actor: ${{github.actor}} ==="
          echo "=== [Get deployment info][params] gh_token: ${{inputs.gh_token}} ==="

          DEPLOYMENTS=$(gh api repos/${{ github.repository }}/deployments)
          echo "deployments=$DEPLOYMENTS" >> $GITHUB_OUTPUT

          echo "=== [Get deployment info][result] NEW_VERSION: $NEW_VERSION ==="

      - name: Generate report
        run: |
          RELEASE_NUMBER = $(echo ${{ github.ref }} | cut -d '/' -f 4)
          echo "=== [Generate report][params] project_name: ${{github.event.repository.name}} ==="
          echo "=== [Generate report][params] ref_name: ${{github.ref_name}} ==="
          echo "=== [Generate report][params] release_number: #11 ==="
          echo "=== [Generate report][params] version: ${{inputs.version}} ==="
          echo "=== [Generate report][params] env: ${{inputs.env}} ==="
          echo "=== [Generate report][params] actor: ${{github.actor}} ==="
          echo "=== [Generate report][params] deployments: ${{steps.get_deploy.outputs.deployments}} ==="

          REPORT_DATA=$(jq -n \
            --arg project_name "${{ github.event.repository.name }}" \
            --arg ref_name "${{ github.ref_name }}" \
            --arg release_number #11 \
            --arg version "${{ inputs.version }}" \
            --arg env "${{ inputs.env }}" \
            --arg actor "${{ github.actor }}" \
            --argjson deployments "${{ steps.get_deploy.outputs.deployments }}" \
            '{
              project_name: $project_name,
              release_number: $release_number,
              version: $version,
              environment: $env,
              actor: $actor,
              deployments: $deployments
            }')

          REPORT_FILE="report_${{ inputs.env }}.txt"

          echo "$REPORT_DATA" > $REPORT_FILE

          echo "=== [Get deployment info][result] REPORT_FILE: report_${{ inputs.env }}.txt ==="

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: deploy-report-${{ inputs.env }}
          path: report_${{ inputs.env }}.txt
