name: Upload Html

run-name: Upload Html

on:
  workflow_call:
    inputs:
      env:
        description: "Environment type (PROD, UAT)"
        required: true
        type: string
        default: "--"

      source:
        description: "source for scp params"
        required: true
        type: string
        default: "./dist/*"

      rm:
        description: "rm for scp params"
        required: true
        type: boolean
        default: true

      strip_components:
        description: "strip_components for scp params"
        required: true
        type: number
        default: 1

  workflow_dispatch:
    inputs:
      env:
        description: "Environment type (PROD, UAT)"
        required: true
        type: string
        default: "PROD"

      source:
        description: "source for scp params"
        required: true
        type: string
        default: "./dist/*"

      rm:
        description: "rm for scp params"
        required: true
        type: boolean
        default: true

      strip_components:
        description: "strip_components for scp params"
        required: true
        type: number
        default: 1

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Console params
        run: |
          echo "=== [Console params][params] env: ${{ inputs.env }} ==="
          echo "=== [Console params][params] source: ${{ inputs.source }} ==="
          echo "=== [Console params][params] rm: ${{ inputs.rm }} ==="
          echo "=== [Console params][params] strip_components: ${{ inputs.strip_components }} ==="
          echo "=== [Console params][secrets] SSH_HOST: ${{ secrets.SSH_HOST }} ==="
          echo "=== [Console params][secrets] SSH_PORT: ${{ secrets.SSH_PORT }} ==="
          echo "=== [Console params][secrets] SSH_USERNAME: ${{ secrets.SSH_USERNAME }} ==="
          echo "=== [Console params][secrets] SSH_KEY: ${{ secrets.SSH_KEY }} ==="
          echo "=== [Console params][github] repository_name: ${{ github.event.repository.name }} ==="

      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ github.event.inputs.source }}
          target: ${{ github.event.inputs.env == 'PROD' && format('{0}/{1}', secrets.SERVER_HTML, github.event.repository.name) || format('{0}/{1}/{2}', secrets.SERVER_HTML, github.event.inputs.env, github.event.repository.name) }}
          rm: ${{ github.event.inputs.rm }}
          strip_components: ${{ github.event.inputs.strip_components }}
