# 工作流名称：上传HTML
name: Upload Html

# 触发条件
on:
  # 被其他工作流调用
  workflow_call:
    # 定义输入参数
    inputs:
      project_name:
        description: "github.event.repository.name"
        required: true
        type: string
        default: "--"

      env:
        description: "Environment type (PROD, UAT)"
        required: true
        type: string
        default: "--"

      # host:
      #   description: "Host IP"
      #   required: true
      #   type: string
      #   default: ""

      # port:
      #   description: "Port"
      #   required: true
      #   type: number
      #   default: 22

      # username:
      #   description: "Username"
      #   required: true
      #   type: string
      #   default: ""

      # key:
      #   description: "Key"
      #   required: true
      #   type: string
      #   default: ""

      source:
        description: "source for scp params"
        required: false
        type: string
        default: "./dist/*"

      rm:
        description: "rm for scp params"
        required: false
        type: boolean
        default: true

      strip_components:
        description: "strip_components for scp params"
        required: false
        type: number
        default: 1

  # 手动触发
  workflow_dispatch:
    # 定义输入参数
    inputs:
      project_name:
        description: "github.event.repository.name"
        required: true
        type: string
        default: "--"

      env:
        description: "Environment type (PROD, UAT)"
        required: true
        type: string
        default: "--"

      # host:
      #   description: "Host IP"
      #   required: true
      #   type: string
      #   default: ""

      # port:
      #   description: "Port"
      #   required: true
      #   type: number
      #   default: 22

      # username:
      #   description: "Username"
      #   required: true
      #   type: string
      #   default: ""

      # key:
      #   description: "Key"
      #   required: true
      #   type: string
      #   default: ""

      source:
        description: "source for scp params"
        required: false
        type: string
        default: "./dist/*"

      rm:
        description: "rm for scp params"
        required: false
        type: boolean
        default: true

      strip_components:
        description: "strip_components for scp params"
        required: false
        type: number
        default: 1

# 定义任务
jobs:
  # 任务名称：upload
  upload:
    # 运行环境：最新版Ubuntu
    runs-on: ubuntu-latest

    # 任务步骤
    steps:
      # 第一步：检出代码
      - uses: actions/checkout@v3

      # 第二步：上传文件
      - name: Upload files
        # 使用SCP Action进行文件上传
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # 目标服务器地址
          port: ${{ secrets.SSH_PORT }} # SSH端口号
          username: ${{ secrets.SSH_USERNAME }} # SSH用户名，从GitHub Secrets获取
          key: ${{ secrets.SSH_KEY }} # SSH Key
          source: ${{ github.event.inputs.source }} # 要上传的文件
          target: ${{ github.event.inputs.env == 'PROD' && format('{0}/{1}', secrets.SERVER_HTML, github.event.inputs.project_name) || format('{0}/{1}/{2}', secrets.SERVER_HTML, github.event.inputs.env, github.event.inputs.project_name) }} # 目标路径
          rm: ${{ github.event.inputs.rm }}
          strip_components: ${{ github.event.inputs.strip_components }}
