name: Upload Html

run-name: Upload Html

on:
  workflow_call:
    inputs:
      env:
        description: "Environment type (prod, uat)"
        required: true
        type: string
        default: "prod"

      repository_name:
        description: "Repository name"
        required: false
        type: string
        default: ""

      rm:
        description: "rm for scp params"
        required: true
        type: boolean
        default: true

      strip_components:
        description: "strip_components for scp params"
        required: true
        type: number
        default: 1

    secrets:
      SSH_HOST:
        required: true
      SSH_PORT:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true
      SERVER_HTML:
        required: true

  workflow_dispatch:
    inputs:
      env:
        description: "Environment type (prod, uat)"
        required: true
        type: string
        default: "prod"

      repository_name:
        description: "Repository name"
        required: false
        type: string
        default: ""

      rm:
        description: "rm for scp params"
        required: true
        type: boolean
        default: true

      strip_components:
        description: "strip_components for scp params"
        required: true
        type: number
        default: 1

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download previous artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: warn

      - name: Get repository name
        id: repo
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "repository_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "Repository name: $REPO_NAME"

      - name: Console params
        run: |
          echo "=== [Console params][params] env: ${{ inputs.env }} ==="
          echo "=== [Console params][params] repository_name: ${{ inputs.repository_name }} ==="
          echo "=== [Console params][params] rm: ${{ inputs.rm }} ==="
          echo "=== [Console params][params] strip_components: ${{ inputs.strip_components }} ==="
          echo "=== [Console params][secrets] SSH_HOST: ${{ secrets.SSH_HOST }} ==="
          echo "=== [Console params][secrets] SSH_PORT: ${{ secrets.SSH_PORT }} ==="
          echo "=== [Console params][secrets] SSH_USERNAME: ${{ secrets.SSH_USERNAME }} ==="
          echo "=== [Console params][secrets] SSH_KEY: ${{ secrets.SSH_KEY }} ==="
          echo "=== [Console params][outputs] repository_name: ${{ steps.repo.outputs.repository_name }} ==="
          echo "=== [Console params][github] repository_name: ${{ github.repository }} ==="
          echo "======"

      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: dist/
          target: ${{ inputs.env == 'prod' && format('{0}/{1}', secrets.SERVER_HTML, inputs.repository_name || steps.repo.outputs.repository_name) || format('{0}/{1}/{2}', secrets.SERVER_HTML, inputs.env, inputs.repository_name || steps.repo.outputs.repository_name) }}
          rm: ${{ inputs.rm }}
          strip_components: ${{ inputs.strip_components }}

      - name: Console Url
        run: |
          echo "=== [Console Url]: ${{ inputs.env == 'prod' && format('{0}/{1}', 'https://orz2.online', inputs.repository_name || steps.repo.outputs.repository_name) || format('{0}/{1}/{2}', 'https://orz2.online', inputs.env, inputs.repository_name || steps.repo.outputs.repository_name) }} ==="
